# Mock AI responses for backend API
# These simulate real AI API responses and will be replaced with actual AI integrations

import random
from typing import Dict, Any, List

def generate_mock_website(description: str, website_type: str = None) -> Dict[str, Any]:
    """Generate mock website data"""
    return {
        "preview": f"""
            <div style="font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto;">
                <header style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 2rem; text-align: center; border-radius: 10px; margin-bottom: 2rem;">
                    <h1 style="margin: 0; font-size: 2.5rem;">Welcome to {website_type or 'Your'} Website</h1>
                    <p style="margin: 0.5rem 0 0 0; opacity: 0.9;">Generated by AI based on: {description[:50]}...</p>
                </header>
                
                <section style="display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 2rem; margin-bottom: 2rem;">
                    <div style="background: #f8f9fa; padding: 1.5rem; border-radius: 10px; border-left: 4px solid #667eea;">
                        <h3 style="color: #333; margin-top: 0;">Feature One</h3>
                        <p style="color: #666;">AI-generated content based on your requirements. Modern, responsive, and optimized.</p>
                    </div>
                    <div style="background: #f8f9fa; padding: 1.5rem; border-radius: 10px; border-left: 4px solid #764ba2;">
                        <h3 style="color: #333; margin-top: 0;">Feature Two</h3>
                        <p style="color: #666;">Professional design with clean layout and user-friendly interface elements.</p>
                    </div>
                </section>
                
                <footer style="text-align: center; padding: 1rem; background: #333; color: white; border-radius: 10px;">
                    <p style="margin: 0;">© 2024 AI Generated Website - Ready to deploy!</p>
                </footer>
            </div>
        """,
        "stats": {
            "files": random.randint(3, 8),
            "components": random.randint(5, 15),
            "responsive": True,
            "seo_score": random.randint(85, 100)
        },
        "features": [
            "Responsive Design", "SEO Optimized", "Modern UI/UX", "Cross-browser Compatible",
            "Mobile-first", "Fast Loading", "Accessible", "Clean Code"
        ],
        "files": [
            {"name": "index.html", "size": "2.4KB", "type": "HTML"},
            {"name": "styles.css", "size": "1.8KB", "type": "CSS"},
            {"name": "script.js", "size": "1.2KB", "type": "JavaScript"}
        ]
    }

def generate_mock_game(idea: str, game_type: str = None, platform: str = "web") -> Dict[str, Any]:
    """Generate mock game data"""
    title_adjectives = ["Epic", "Mystical", "Ultimate", "Legendary", "Incredible", "Amazing"]
    title = f"{random.choice(title_adjectives)} {game_type or 'Adventure'}"
    
    return {
        "title": title,
        "description": f"An AI-generated {game_type or 'adventure'} game based on your concept: {idea[:100]}...",
        "icon": "🎮",
        "stats": {
            "levels": random.randint(5, 25),
            "assets": random.randint(15, 60),
            "code_lines": random.randint(800, 5000),
            "playtime": f"{random.randint(2, 12)}h"
        },
        "features": [
            "Smooth Gameplay", "Dynamic Difficulty", "Achievement System", "Save/Load Game",
            "Multiple Levels", "Sound Effects", "Particle Effects", "Leaderboard"
        ],
        "tech_stack": [
            "HTML5 Canvas" if platform == "web" else "Native Code",
            "JavaScript", "WebGL", "Audio API", "LocalStorage"
        ],
        "gameplay_mechanics": [
            "Physics-based movement", "Collision detection", "Score system", "Power-ups"
        ]
    }

def generate_mock_content(topic: str, content_type: str, tone: str, length: str) -> Dict[str, Any]:
    """Generate mock content data"""
    word_counts = {"short": 350, "medium": 650, "long": 1200}
    word_count = word_counts.get(length, 650)
    sentences = word_count // 15
    
    content = f"""
        <h2>The Future of {topic}</h2>
        <p>In today's rapidly evolving digital landscape, {topic} has become increasingly important for businesses and individuals alike. This comprehensive analysis explores the various aspects and implications of this fascinating subject.</p>
        
        <h3>Key Benefits and Advantages</h3>
        <p>The implementation of {topic} offers numerous advantages including improved efficiency, enhanced user experience, and cost-effective solutions. Organizations that embrace these innovations often see significant improvements in their operations.</p>
        
        <h3>Current Trends and Developments</h3>
        <p>Recent developments in {topic} have shown remarkable progress. Industry leaders are investing heavily in research and development, leading to breakthrough innovations that are reshaping the entire sector.</p>
        
        <h3>Looking Forward</h3>
        <p>As we move into the future, {topic} will continue to play a crucial role in shaping our digital world. The potential applications are limitless, and we're only beginning to scratch the surface of what's possible.</p>
        
        <p><strong>Conclusion:</strong> The journey ahead is exciting, and those who adapt early will be best positioned to take advantage of these emerging opportunities.</p>
    """
    
    return {
        "content": content,
        "stats": {
            "words": word_count,
            "sentences": sentences,
            "read_time": f"{max(1, word_count // 200)}min",
            "seo_score": random.randint(75, 95)
        },
        "features": [
            "SEO Optimized", "Engaging Headlines", "Clear Structure", "Call-to-Action",
            "Keyword Rich", "Scannable Format", f"{tone.title()} Tone"
        ],
        "keywords": [topic.lower(), f"{topic.lower()} benefits", f"future of {topic.lower()}"],
        "readability_score": random.randint(70, 90)
    }

def generate_mock_images(prompt: str, style: str, size: str, quality: str) -> Dict[str, Any]:
    """Generate mock image data"""
    image_count = 4
    images = []
    
    for i in range(image_count):
        images.append({
            "url": f"https://picsum.photos/400/400?random={random.randint(1, 1000)}",
            "description": f"AI generated {style} image based on: '{prompt[:50]}...'",
            "style": style,
            "resolution": size,
            "file_size": f"{random.randint(1, 8)}MB",
            "format": "PNG",
            "quality_score": random.randint(85, 98)
        })
    
    return {
        "images": images,
        "generation_info": {
            "model": "Mock AI Image Generator v2.0",
            "style_applied": style,
            "prompt_processed": prompt,
            "total_images": len(images)
        }
    }

def generate_mock_code(request: str, language: str, task_type: str = None) -> Dict[str, Any]:
    """Generate mock code data"""
    
    code_templates = {
        "javascript": f"""
// {task_type or 'Function'} - Generated by AI
function {(task_type or 'solution').replace(' ', '').lower()}() {{
    // AI-generated code based on: {request[:50]}...
    
    const result = {{
        status: 'success',
        data: [],
        timestamp: new Date().toISOString()
    }};
    
    // Main logic implementation
    try {{
        console.log('Processing request:', '{request[:30]}...');
        
        // Your custom logic here
        // This is a mock implementation
        
        return result;
    }} catch (error) {{
        console.error('Error:', error);
        return {{ status: 'error', message: error.message }};
    }}
}}

// Usage example
const output = {(task_type or 'solution').replace(' ', '').lower()}();
console.log(output);
        """,
        
        "python": f"""
# {task_type or 'Function'} - Generated by AI
def {(task_type or 'solution').replace(' ', '_').lower()}():
    \"\"\"
    AI-generated code based on: {request[:50]}...
    \"\"\"
    
    result = {{
        'status': 'success',
        'data': [],
        'timestamp': str(datetime.now())
    }}
    
    try:
        print(f"Processing request: {request[:30]}...")
        
        # Your custom logic here
        # This is a mock implementation
        
        return result
        
    except Exception as e:
        print(f"Error: {{e}}")
        return {{'status': 'error', 'message': str(e)}}

# Usage example
output = {(task_type or 'solution').replace(' ', '_').lower()}()
print(output)
        """
    }
    
    code = code_templates.get(language, code_templates["javascript"])
    
    return {
        "language": language.upper(),
        "code": code,
        "stats": {
            "lines": len(code.split('\n')),
            "functions": random.randint(1, 5),
            "complexity": random.choice(["Low", "Medium", "High"]),
            "quality": f"{random.randint(85, 98)}%"
        },
        "features": [
            "Error Handling", "Documentation", "Clean Code", "Best Practices",
            "Optimized Performance", "Type Safety", "Modular Design"
        ],
        "explanation": f"This {language} code implements {(task_type or 'the requested functionality').lower()} based on your requirements. It includes proper error handling, clear variable names, and follows best practices for maintainable code.",
        "dependencies": ["datetime"] if language == "python" else [],
        "testing_suggestions": [
            "Unit tests for core functions",
            "Integration tests",
            "Error handling tests"
        ]
    }

def generate_mock_data_analysis(data_input: str, analysis_type: str, data_source: str) -> Dict[str, Any]:
    """Generate mock data analysis results"""
    
    return {
        "confidence": random.randint(75, 95),
        "metrics": {
            "data_points": random.randint(500, 10000),
            "accuracy": f"{random.randint(80, 98)}%",
            "patterns": random.randint(3, 12),
            "insights": random.randint(5, 15)
        },
        "chart": {
            "type": "Interactive Dashboard",
            "icon": "📊",
            "description": "Multi-dimensional visualization showing trends, patterns, and correlations in your data."
        },
        "insights": [
            {
                "icon": "📈",
                "title": "Significant Growth Trend",
                "description": f"Data shows a {random.randint(15, 35)}% upward trend in the analyzed metrics over the examined period.",
                "impact": "High",
                "confidence": random.randint(85, 95)
            },
            {
                "icon": "🔍",
                "title": "Pattern Recognition",
                "description": f"Identified recurring patterns that occur every {random.randint(3, 14)}-day cycle with {random.randint(80, 95)}% consistency.",
                "impact": "Medium",
                "confidence": random.randint(75, 90)
            },
            {
                "icon": "⚡",
                "title": "Anomaly Detection",
                "description": f"Found {random.randint(1, 8)} significant outliers that may require attention or further investigation.",
                "impact": "Medium",
                "confidence": random.randint(70, 85)
            }
        ],
        "recommendations": [
            "Implement predictive modeling", "Set up automated monitoring", "Create data pipeline",
            "Schedule regular analysis", "Deploy ML algorithms", "Establish alerts for anomalies"
        ],
        "data_quality": {
            "completeness": f"{random.randint(85, 100)}%",
            "consistency": f"{random.randint(80, 95)}%",
            "accuracy": f"{random.randint(88, 98)}%"
        }
    }

def generate_mock_creative_content(prompt: str, creative_type: str, style: str, mood: str = None) -> Dict[str, Any]:
    """Generate mock creative content"""
    
    contents = {
        "poem": f"""In digital realms where dreams take flight,
AI whispers through the night,
Creating worlds with lines of code,
Along imagination's winding road.

Binary stars in cyber space,
Dance with algorithmic grace,
While pixels paint what hearts conceive,
In this world we make believe.

The future flows through circuits bright,
Where human dreams and data unite,
In harmony of mind and machine,
The most beautiful sight ever seen.

{mood or 'Wonder'} fills the air tonight,
As {prompt[:20]}... comes into sight.""",
        
        "story": f"""The old lighthouse keeper had seen many storms, but none quite like this. As the waves crashed against the rocky shore, she noticed something unusual in the water—a soft, ethereal glow that seemed to pulse with the rhythm of the tide.

"Strange," she murmured, adjusting her weathered coat against the wind. For forty years, she had watched over this stretch of coast, guiding ships safely home. But tonight felt different. Tonight, {prompt[:30]}... seemed to be calling her name.

The glow grew brighter, revealing what appeared to be a message written in the foam itself—letters that formed and dissolved with each wave. She leaned forward, squinting through the storm, and gasped as she finally made out the words.

In that moment, she understood that every ship she had guided, every life she had touched, had become part of something greater—a network of gratitude spanning decades and oceans. The {mood or 'mysterious'} feeling she'd had all evening finally made sense.""",
        
        "song": f"""[Verse 1]
Walking down this neon street tonight
City lights are burning bright
{prompt[:30]}... is on my mind
Leaving all my fears behind

[Chorus]
We're reaching for tomorrow
Through the joy and through the sorrow
Every step we take today
Lights the path along the way

[Verse 2]
Stars are dancing overhead
Painting silver, gold, and red
Music flowing through the air
Magic moments everywhere

[Bridge]
In this {mood or 'hopeful'} atmosphere
All our dreams are drawing near
{style.title()} melodies arise
Underneath the starlit skies

[Chorus]
We're reaching for tomorrow
Through the joy and through the sorrow
Every step we take today
Lights the path along the way"""
    }
    
    selected_content = contents.get(creative_type, contents["poem"])
    word_count = len(selected_content.split())
    
    return {
        "title": f"{style.title()} {creative_type.title()}",
        "type": creative_type,
        "style": style,
        "content": selected_content,
        "stats": {
            "words": word_count,
            "verses": selected_content.count('\n\n') + 1 if creative_type == "poem" else None,
            "paragraphs": selected_content.count('\n\n') + 1 if creative_type != "poem" else None,
            "read_time": f"{max(1, word_count // 200)}min",
            "creativity": f"{random.randint(80, 98)}%"
        },
        "elements": [
            "Metaphor", "Imagery", "Rhythm", "Emotional Depth",
            "Symbolism", "Flow", "Vivid Language", f"{mood or 'Evocative'} Tone"
        ],
        "analysis": f"This {creative_type} demonstrates strong {style} influences with {mood or 'contemplative'} undertones. The work successfully balances creative expression with structural integrity, creating an engaging piece that resonates with the intended audience.",
        "literary_devices": ["Alliteration", "Metaphor", "Symbolism", "Imagery"],
        "mood_rating": random.randint(85, 95)
    }